site_name: HuCon
site_description: 'HuCon documentation about the full featured robot'
copyright: 'Basler AG 2019'

nav:
    - Home: index.md
    - Inital setup: initial_setup.md
    - license.md

theme:
  name: 'material'
  logo: 'images/icon.svg'
  favicon: 'images/icon.ico'
  palette:
    primary: 'blue'
    accent: 'light blue'

extra_css:
  - 'css/extra.css'

markdown_extensions:
  - admonition
  - attr_list
  - codehilite:
      guess_lang: false
  - tables
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
